jobs:
  - job: BuildLinuxWithGradleSonarCloud
    displayName: Build for Linux\Gradle CFamily With SonarCloud
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: SonarCloudPrepare@3
        inputs:
          SonarCloud: 'sonarcloud.io'
          organization: 'luis-rodriguezfernandez-sonarsource'
          scannerMode: 'other'
          extraProperties: |
            sonar.projectKey=demo-gradle-cpp
            sonar.sources=app/src
            sonar.cfamily.compile-commands=bw-output/compile_commands.json

      - bash: |
         sudo apt install -y bear
        displayName: Install bear, a generator compilation database for CFamily projects

      - bash: |
          mkdir bw-output
          gradle --daemon
          bear --output bw-output/compile_commands.json -- gradle clean build sonar --info
        displayName: Build in bear wrapper, generate the compilation database, build the project and run SonarCloud analysis

