jobs:
  - job: BuildLinuxWithGradleSonarCloud
    displayName: Build for Linux\Gradle CFamily With SonarCloud
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: SonarCloudPrepare@3
        inputs:
          SonarCloud: 'sonarcloud.io'
          organization: 'luis-rodriguezfernandez-sonarsource'
          scannerMode: 'other'
          extraProperties: |
            sonar.projectKeydemo-gradle-cpp
            sonar.sources=app/src
            sonar.cfamily.compile-commands=bw-output/compile_commands.json
            sonar.verbose=true

      - bash: |
         sudo apt install -y bear
        displayName: Install bear, a generator compilation database for CFamily tooling

      - bash: |
          mkdir bw-output
          gradle --daemon
          bear --output bw-output/compile_commands.json --verbose -- gradle clean build sonar
        workingDirectory: .
        displayName: Build in bear wrapper and generate the compilation database

#      - task: SonarCloudAnalyze@3
#        displayName: Run SonarCloud analysis
