jobs:
  - job: BuildLinuxWithGradleSonarCloud
    displayName: Build for Linux\Gradle CFamily With SonarCloud
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889.zip

    steps:
      - task: SonarCloudPrepare@3
        inputs:
          SonarCloud: 'sonarcloud.io'
          organization: 'luis-rodriguezfernandez-sonarsource'
          scannerMode: 'cli'
          extraProperties: |
            sonar.projectKey=demo-gradle-cpp
            sonar.sources=src
            sonar.cfamily.compile-commands=bw-output/compile_commands.json

      - bash: |
          sudo apt install -y bear
        displayName: Install bear, a generator compilation database for CFamily projects

      - bash: |
          mkdir bw-output
          gradle --daemon
          bear --output bw-output/compile_commands.json -- gradle clean build
        displayName: Build in bear wrapper, generate the compilation database

      - bash: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner-cli-7.1.0.4889.zip ${{variables.SONAR_SCANNER_DOWNLOAD_URL}}
          unzip -o $HOME/.sonar/sonar-scanner-cli-7.1.0.4889.zip -d $HOME/.sonar/
          export PATH=$HOME/.sonar/sonar-scanner-7.1.0.4889/bin:$PATH
          sonar-scanner
        displayName: Download and run sonar-scanner

